- name: Roboshop Project - Frontend
  hosts: all
  become: true
  tasks:
    - name: Installing NGINX
      ansible.builtin.yum:
        name: nginx
        state: latest

    - name: Starting & Enabling NGINX
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes