- name: Configuring the repo for NodeJS.
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing NodeJS & bash-completion package.
  ansible.builtin.yum:
    name:
      - nodejs
      - bash-completion
    state: installed

- name: App Pre-Requisite
  ansible.builtin.import_tasks: app-preq.yml

- name: Installing the dependencies for the Application- /app/package.json.
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Schema Setup
  ansible.builtin.import_tasks: mongo-schema.yml

- name: Systemd Setup
  ansible.builtin.import_tasks: systemd-setup.yml
