- name: Roboshop Project - RabbitMQ Configuration.
  hosts: all
  become: yes
  tasks:
    - name: Configure the erlang repository.
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

    - name: Configure the RabbitMQ repository.
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

    - name: Install RabbitMQ & Bash-Completion
      ansible.builtin.yum:
        name:
          - rabbitmq-server
          - bash-completion
        state: installed

    - name: Start and Enable the RabbitMQ systemd  service.
      ansible.builtin.systemd:
        name: rabbitmq-server
        state: restarted
        enabled: yes

    - name: Configure the erlang repository.
      ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123 ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
