- name: Set Hostname
  ansible.builtin.shell: set-hostname frontend

- name: Installing NGINX Web-Server
  ansible.builtin.yum:
    name:
      - nginx
      - bash-completion
    state: latest

- name: Configuring the NGINX reverse-proxy.
  ansible.builtin.copy:
    src: nginx-proxy.conf
    dest: /etc/nginx/default.d/nginx-proxy.conf

- name: Removing the existing Web-Server files.
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Creating Application directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Downloading & Extracting the Web-Server content.
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Starting & Enabling NGINX
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: true
