- name: Configure the erlang repository.
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Configure the RabbitMQ repository.
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Install RabbitMQ
  ansible.builtin.yum:
    name:
      - rabbitmq-server
      - bash-completion
    state: installed

- name: Start and Enable the RabbitMQ systemd  service.
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Add RabbitMQ user.
  community.rabbitmq.rabbitmq_user:
    user: rabbitmq
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
