- name: Creating Application User- roboshop.
  ansible.builtin.user:
    name: roboshop

- name: Removing the existing Application Directory.
  ansible.builtin.file:
    path: /app
    state: absent

- name: Creating Application directory.
  ansible.builtin.file:
    path: /app
    state: directory

- name: Downloading & Extracting the {{component}} content.
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes