- name: NodeJS repository configuration.
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS Package.
  ansible.builtin.yum:
    name:
      - nodejs
      - bash-completion
    state: installed

- name: App Pre-Requisite
  ansible.builtin.import_tasks: app-preq.yml

- name: Install Application Dependency:- /app/package.json.
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Schema Setup
  ansible.builtin.import_tasks: mongo-schema.yml
  when: schema is defined

- name: Systemd Setup
  ansible.builtin.import_tasks: systemd-setup.yml
